name: project_integre
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following are General tools
  get: ^4.6.5
  prefs: ^4.0.0
  email_validator: ^2.1.17
  http: ^0.13.5
  get_storage: ^2.0.3

  # The following is for database management
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.3.0

  # The following is for images and animations
  lottie: ^2.0.0
  flutter_svg: ^1.1.6

  #the following is for ui elemenets
  settings_ui: ^2.0.2
  curved_navigation_bar: ^1.0.3
  widget_circular_animator: ^1.0.0
  circular_profile_avatar: ^2.0.5
  image_picker: ^0.8.6
  eva_icons_flutter: ^3.1.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  chips_choice: ^3.0.0
  dropdown_button2: ^1.9.2
  searchbar_animation: ^0.0.4
  motion_toast: ^2.6.4
  syncfusion_flutter_calendar: ^20.4.42
  date_time_picker: ^2.1.0
  excel: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/
